{% set name = "napari-lazy-openslide" %}
{% set version = "0.3.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/napari-lazy-openslide-{{ version }}.tar.gz
  sha256: faf95a770b6a99ccd8c0e04bc6d2431c270258bb8912169e277377e6bc31f4d7

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
    - setuptools-scm
  run:
    - dask-core >=2.20.0
    - napari-plugin-engine >=0.1.4
    - numpy >=1.19
    - openslide-python >=1.1.2
    - python >={{ python_min }}
    - zarr >=0.2.4

test:
  imports:
    - napari_lazy_openslide
  commands:
    - pip list
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/manzt/napari-lazy-openslide
  summary: A plugin to lazily load multiscale whole-slide images with openslide and dask.
  license: BSD-3-Clause
  license_file: LICENSE

extra:
  recipe-maintainers:
    - goanpeca
    - jaimergp
    - manzt
